name: build-win
on: [workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - run: gem install eventmachine --platform ruby
      - run: gem install ocra lmcadm
      - run: ruby makeocragemfile.rb
      - run: ocra --gemfile ocra_gemfile --gem-full exe/lmcadm
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: false
      - run: ./lmcadm.exe version
      - uses: papeloto/action-zip@v1
        with:
          files: lmcadm.exe LICENSE.txt
          dest: ${{ github.event.release.tag_name }}-win.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.event.release.tag_name }}-win.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

